version: '2.1'
services:
  portal:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - ../tomcat85/default.conf:/etc/nginx/conf.d/default.conf
    links:
     - tomcatServerOne:tomcat1
     - tomcatServerTwo:tomcat2
  tomcatServerOne:
    image: tomcat:8.5-jdk8
    ports:
     - "8080"
    volumes:
     - ../target/example.war:/usr/local/tomcat/webapps/example.war
     - ../target/example.war:/usr/local/tomcat/webapps/example2.war
     - ../tomcat85/hazelcast-tomcat85-sessionmanager-1.1.5.jar:/usr/local/tomcat/lib/hazelcast-tomcat85-sessionmanager-1.1.5.jar
     - ../tomcat85/hazelcast-all-3.11.2.jar:/usr/local/tomcat/lib/hazelcast-all-3.11.2.jar
     - ../tomcat85/server.xml:/usr/local/tomcat/conf/server.xml
     - ../tomcat85/context.xml:/usr/local/tomcat/conf/context.xml
  tomcatServerTwo:
    image: tomcat:8.5-jdk8
    ports:
     - "8080"
    volumes:
     - ../target/example.war:/usr/local/tomcat/webapps/example.war
     - ../target/example.war:/usr/local/tomcat/webapps/example2.war
     - ../tomcat85/hazelcast-tomcat85-sessionmanager-1.1.5.jar:/usr/local/tomcat/lib/hazelcast-tomcat85-sessionmanager-1.1.5.jar
     - ../tomcat85/hazelcast-all-3.11.2.jar:/usr/local/tomcat/lib/hazelcast-all-3.11.2.jar
     - ../tomcat85/server.xml:/usr/local/tomcat/conf/server.xml
     - ../tomcat85/context.xml:/usr/local/tomcat/conf/context.xml
